### ISSUE TITLE
Second "Welcome" is private and a old room thats not used anymore.

### ISSUE THREAD

**Issue by geecrumb** [tharushkadinujaya05/TryHackMe-Learning-Path-From-Beginner-to-Expert#1]
Second "Welcome" is private and a old room thats not used anymore.

https://tryhackme.com/r/room/welcome

**Comment by 0xneobyte** [comment]
https://tryhackme.com/r/room/hello

Here is the working link of the "Welcome" room. yeah above link is outdated i will remove that
